services:
  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=leetcode
      - POSTGRES_USER=leetcode
      - POSTGRES_DB=leetcode
volumes:
  pgdata: